### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by marek22k** [dadevel/wg-netns#12]
It seems that the WireGuard interface is configured in the namespace, but it should be configured in the init namespace (for DNS resolution to work):
```
Temporary failure in name resolution: `p2p-router.de:52924'. Trying again in 1.00 seconds...
Temporary failure in name resolution: `p2p-router.de:52924'. Trying again in 1.20 seconds...
Temporary failure in name resolution: `p2p-router.de:52924'. Trying again in 1.44 seconds...
Temporary failure in name resolution: `p2p-router.de:52924'. Trying again in 1.73 seconds...
Temporary failure in name resolution: `p2p-router.de:52924'. Trying again in 2.07 seconds...
Temporary failure in name resolution: `p2p-router.de:52924'. Trying again in 2.49 seconds...
```
```
name: dn42
managed: false
base_netns: null
post-up: ip addr add dev bandura2 fe80::2924/128 peer fe80::2923/128
interfaces:
  - name: bandura2
    private-key: [some key]
    mtu: 1420
    peers:
      - public-key: bgSz1aqV9otL3uUiyBqdA7kdw3aE+itwoH4xjINi+0U=
        preshared-key: [some key]
        endpoint: p2p-router.de:52924
        allowed-ips:
          - fd00::/8
          - fe80::/10
        routes: []
```
