### ISSUE TITLE
Allow running post-up and friends in the host namespace

### ISSUE THREAD

**Issue by chrisbouchard** [dadevel/wg-netns#6]
I would like for `wg-netns`'s configuration to provide a way to run `post-up` and similar commands in the host network namespace, rather than the managed network namespace.

For my use-case, I want to create a veth pair to connect the managed namespace to the host namespace. It seemed natural to do this as a `post-up` command (and tear it down as a `pre-down` command), but that turned out to be difficult because all commands run in the managed namespace, and the veth has to be created in the host namespace and then moved into the managed namespace (just like we do with the WireGuard interface).

My current work-around is to use `nsenter`. I can't use `ip netns exec` because the host namespace is the unnamed root namespace. So I have the following:

```yaml
name: vpn
managed: true

post-up: |
  nsenter --target 1 --net <<EOF &&
    ip link add vpn-veth type veth peer host-veth &&
      ip link set host-veth netns vpn &&
      ip addr add 10.0.1.1/24 dev vpn-veth
  EOF
    ip addr add 10.0.1.2/24 dev host-veth

pre-down: |
  nsenter --target 1 --net ip link delete vpn-veth || true
```

This results in `wg-netns` actually running `ip netns exec vpn nsenter --target 1 --net ...`, which is a bunch of unnecessary redirection. It also makes the assumption that the namespace I need is the one from PID 1, which is true in my case but wouldn't be if I'd run `wg-netns` in a different namespace. (I don't know any reliable way to get the host namespace other than trying to search for the `wg-netns` process to get its PID.)

It would be a lot nicer if I could run actions in the host namespace directly rather than the managed namespace.

One approach would be to just change how `post-up` and friends work, and have them run in the host namespace. We could then use `ip netns exec vpn ...` for commands that need to run in the managed namespace, since that name is fixed in the config file. This would of course be an invisible breaking change for existing configurations.

I suppose another approach would be to provide new options in `interfaces` to build veth interfaces in addition to WireGuard, but that seems short-sighted given that others may want a bridge or some other type of interface.

I think my preferred approach would be to introduce new command syntax. Here's my suggestion:

```yaml
name: vpn
managed: true

post-up:
  - ~:
    - ip link add vpn-veth type veth peer host-veth
    - ip link set host-veth netns vpn
    - ip addr add 10.0.1.1/24 dev vpn-veth
  - vpn:
    - ip addr add 10.0.1.2/24 dev host-veth

pre-down:
  - ~:
    - ip link delete mullvad-veth || true
```

So `post-up` and friends would accept (in addition to the current string format) a list of hashes. The keys would be the namespace name to pass to `ip netns exec`, and if the key is null (`~` in YAML) or maybe blank (since I'm not sure if JSON supports null keys) then the command is run in the host namespace. The values would be a list of commands to run in that namespace. All commands would be run in sequence.

I can think of two potential shorthands. One would be to allow a single string instead of the inner list, which would be a singleton command. The second would be to allow strings in the outer list directly, which would run in some default namespace&#8202;&mdash;&#8202;the host namespace would be most convenient for me, but the managed namespace would be reasonable to match the existing behavior for a single string value.

Assuming we chose for a string to run in the host namespace, my example above could be equivalently and concisely written:

```yaml
name: vpn
managed: true

post-up:
  - ip link add vpn-veth type veth peer host-veth
  - ip link set host-veth netns vpn
  - ip addr add 10.0.1.1/24 dev vpn-veth
  - vpn: ip addr add 10.0.1.2/24 dev host-veth

pre-down:
  - ip link delete mullvad-veth || true
```

I think we could reasonably preprocess the different command structures (including the current string format) to a new `Command` type, which would provide an `exec` method or similar. If this is something you'd be interested in, I'd be happy to help with implementation.

**Comment by dadevel** [comment]
Hey, that's a nice idea. Thanks for the detailed explanation.

I would like a bit more explicit syntax. What do you think about the following?

~~~ yaml
post-up:
- echo hello world  # backwards compatibility, runs inside the network namespace created by wg-netns
- namespace: self  # explicit version of the command above
  command: echo hello world
- namespace: host  # inspired by "docker run --network host"
  command: |
    echo 1
    echo 2
    echo 3
- namespace: vpn  # any other network namespace, is this feature needed?
  command: echo 42
~~~

**Comment by chrisbouchard** [comment]
I'm a fan of this more explicit style. The only thing I would caution against is using `host` for the host namespace&#8202;&mdash;&#8202;it makes sense for Docker because the network options are essentially an enum they control, but in our case it's a free-form string outside of our control. I think &ldquo;host&rdquo; could reasonably be the name of an existing namespace, e.g., containing a web host.

I'd suggest perhaps one of the following:

* Using null, which could be written `~` or `null` in YAML (while still allowing `"null"` to refer to a namespace named &ldquo;null,&rdquo; because unlike `host`, `null` is a keyword);
* Using a value that is not accepted by `ip netns add` (e.g., `/`, but that could be confusing because the host magnesian is not necessarily the *root* namespace);
* Using a separate property to indicate the host namespace, e.g., `host-namespace: true`.

As for whether be should support arbitrary namespace names, I think we should. My current use-case doesn't require it, but I could see someone wanting to create a tunnel between the managed namespace and an unrelated existing namespace.

**Comment by chrisbouchard** [comment]
Oh, I missed the `self` value in my previous read. I think the same arguments apply as for `host`. (Though I'm having a harder time imagining why someone would be using that name&#8202;&mdash;&#8202;maybe as a global alias for the root namespace? ¯\\\_(ツ)\_/¯)

I guess that takes my option 1 off the table because we have two non-named namespaces to handle. (I guess we don't *need* special support for the self/managed namespace, since the config author chose it, but since you suggested it I agree it seems natural.)

One other possibility would be to treat `namespace` as an enum and use an application-local tag for named namespaces&#8202;&mdash;&#8202;so something like the following:

```yaml
namespace: host
namespace: self
namespace: !named vpn
```

I don't know how easy it is to handle arbitrary tags in PyYAML, and of course that doesn't work in JSON. So maybe not an option, but I wanted to mention it.

**Comment by dadevel** [comment]
I would like to keep JSON compatibility as you already mentioned.
I think the easiest solution would be to drop my `self` idea and just use `namespace: ~` / `namespace: null` to referrer to the host netns.

**Comment by chrisbouchard** [comment]
I can dig it. 👍

Is this something you'd like to tackle yourself? Our would you be interested in a pull request?

**Comment by dadevel** [comment]
I welcome every PR :D

**Comment by chrisbouchard** [comment]
I started implementing this, and I ran into a complication handling `namespace`. I started with a pretty simple data structure:

```python
@dataclass
class ScriptletItem:
    command: str
    namespace: Optional[str] = None

@dataclass
class Scriptlet:
    items: list[ScriptletItem] = # ...
```

The trouble is how to represent the simple form of an item, which is meant to run in the managed/self namespace, versus the explicit form with `namespace: null`, which is meant to run in the host namespace. We'd either need two different item types (with and without namespace) or a more complicated item type (that tracks whether null means host or self).

While neither approach is too difficult to implement, it got me thinking that the same thing may be confusing for end-users. We're treating an explicitly null namespace differently than we treat an implicitly unset namespace, and while this is supported by both JSON and YAML, there's often an implicit assumption that unset is equivalent to null.

This further got me thinking about what you asked in your first example: Do we actually need to reference other named namespaces? I answered yes, because it might be convenient, but we don't really because users can always use an explicit `ip netns exec` in the command&#8202;&mdash;&#8202;as long as the command runs in the host namespace, this is no less efficient than us doing it for them, and maybe explicit *is* better than implicit here.

What would you think of a simpler approach, where the items look like

```yaml
post-up:
  - run-in-host-ns: true  # Explicitly run in the host namespace
    command: |
      echo foo
  - run-in-host-ns: false  # Falsy values (including null) run in the self namespace
    command: |
      echo bar
  - command: |  # We can treat unset run-in-host-ns equivalently to null/false
      echo bar
  - echo bar  # And the simple form is equivalent to the explicit form with run-in-host-ns unset
  - run-in-host-ns: true
    command: |
      ip netns exec another-ns echo blah
  - run-in-host-ns: true  # It is slightly more inconvenient to run multiline commands in a "third-party" namespace
    command: |
      ip netns exec another-ns sh <<<EOF
        echo hello
        echo world
      EOF
```

I don't mean to waffle on this too much&#8202;&mdash;&#8202;I just think that I may have pushed for unnecessary complexity. I'll be happy to keep going with the previous design if you prefer it.
